config/routes.rb
Rails.application.routes.draw do

  resources :articles

  root 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    @article = Article.new

  end

  def create
    @article = Article.create(article_params)
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def edit
    @article = Article.find(params[:id])
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update(article_params)
        format.html {}
        format.js {}
      else
        flash[:alert] = "Something went wrong, Data not updated"
        render root_path
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html {redirect_to root_path}
      format.js {}
    end
  end

  private
    def article_params
      params.require(:article).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
%li{:id => "#{article.id}"}
  = article.title
  %br
  %strong body:
  = "#{article.body}"
  %br
  = link_to 'Edit', edit_article_path(article), remote: true
  = link_to 'Delete', article_path(article) , method: 'delete', remote: true

app/views/articles/_form.html.haml
= form_with model: @article do |f|
  .form-group
    = f.text_field :title
  %br
  .form-group
    = f.text_field :body
  %br
  .form-group
    = f.submit

app/views/articles/create.js.haml
$('ul').append("#{j render partial: 'article', locals: {article: @article}}");
$('form')[0].reset();

app/views/articles/destroy.js.haml
$("li##{@article.id}").remove();

app/views/articles/edit.js.haml
$("form").replaceWith("#{j render(:partial => "form")}")

app/views/articles/index.html.haml
%h1
  Articles
%hr
%br
= render :partial => 'form'
%br
%ul
  = render @articles

app/views/articles/update.js.haml
$("li##{@article.id}").replaceWith("#{j render partial: 'article', locals: {article: @article}}");
- @article = Article.new
$("form").replaceWith("#{j render :partial => 'form'}");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>